local source = debug.getinfo(1, "S").source:sub(2)
local plugin_root = vim.fn.fnamemodify(source, ":p:h:h")
local projects = vim.fn.fnamemodify(plugin_root, ":h")
local root = "/tmp/quickfix-review-differ-demo"
local differ_root = vim.env.DIFFER_PATH or vim.fn.expand("~/projects/differ.nvim")
vim.fn.delete(root, "rf")
vim.fn.mkdir(root, "p")
vim.fn.writefile({ "one", "two", "three", "four" }, root .. "/README.md")
assert(vim.system({ "git", "init", "-q", root }):wait().code == 0)
assert(vim.system({ "git", "-C", root, "add", "." }):wait().code == 0)
assert(vim.system({ "git", "-C", root, "-c", "user.name=Demo", "-c", "user.email=demo@example.com", "commit", "-qm", "base" }):wait().code == 0)
vim.fn.writefile({ "one", "two (changed)", "three (changed)", "four" }, root .. "/README.md")
vim.opt.rtp:prepend(differ_root)
vim.o.termguicolors = true
vim.cmd("runtime plugin/differ.lua")
vim.opt.rtp:prepend(vim.env.QUICKFIX_ACTIONS_PATH or (projects .. "/quickfix-actions.nvim"))
vim.opt.rtp:prepend(vim.env.QUICKFIX_EXPORT_PATH or (projects .. "/quickfix-export.nvim"))
vim.opt.rtp:prepend(plugin_root)
vim.cmd.cd(vim.fn.fnameescape(root))
require("differ").setup({ layout = "split" })
require("quickfix_review").setup({ nerd_font = false, persist_review_list = false, scope_policy = "repository" })
